config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :summons, controllers: { sessions: "summons/sessions", registrations: "summons/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Main Paths
  root 'homes#landing'

  get '/login/role' => 'homes#loginrole'
  get '/signup/role' => 'homes#signuprole'


  # User Paths
  get '/vehicles' => 'vehicles#index', as: 'user'



  get '/carparks' => 'carparks#index', as: 'carparks'
  get '/carparks/new' => 'carparks#new', as: 'new_carpark'
  post '/carparks' => 'carparks#create'
  get '/carparks/:id' => 'carparks#show' , as: 'carpark'
  get '/carparks/:id/edit' => 'carparks#edit', as: 'edit_carpark'
  patch '/carparks/:id' => 'carparks#update'
  delete '/carparks/:id' => 'carparks#destroy'

  get '/carparks/:id/lots' => 'lots#index', as: 'lots'
  get '/carparks/:id/lots/new' => 'lots#new', as: 'new_lot'
  post '/carparks/:id/lots' => 'lots#create'
  get '/lots/:id' => 'lots#show' , as: 'lot'
  get '/lots/:id/edit' => 'lots#edit', as: 'edit_lot'
  patch '/lots/:id' => 'lots#update'
  delete '/lots/:id' => 'lots#destroy'


  get '/regions' => 'regions#index', as: 'regions'
  #get '/regions/new' => 'regions#new', as: 'new_region'
  #post '/regions' => 'regions#create'
  get '/regions/:id' => 'regions#show' , as: 'region'
  #get '/regions/:id/edit' => 'regions#edit', as: 'edit_region'
  #patch '/regions/:id' => 'regions#update'
  #delete '/regions/:id' => 'regions#destroy'









  get 'carparks/:id/offences/' => 'offences#index', as: 'offences'
  get 'carparks/:id/offences/new' => 'offences#new', as: 'new_offence'
  post 'carparks/:id/offences/' => 'offences#create'
  get '/offences/:id' => 'offences#show' , as: 'offence'

  get '/admins/' => 'homes#index', as: 'admin'
  get '/summons/' => 'homes#landing', as: 'summon'
end

app/models/offence.rb
class Offence < ActiveRecord::Base
  belongs_to :lot
end

app/controllers/offences_controller.rb
class OffencesController < ApplicationController
 before_action :authenticate_summon!, :except => [:show, :index, :edit, :update, :destroy]
  def index
    @offences = Offence.all.order(:offendingPlateNumber)
  end

  def new
    @carpark = Carpark.find(params[:id])
  end

  def create
    @carpark = Carpark.find(params[:id])
    puts params[:offence].values[0]
    puts params[:offence].values[1]
    @offence = Offence.new(offence_params)
    if @offence.save
    @offence.update(carpark_id: @carpark.id)
    redirect_to @offence
    else
      @carpark = Carpark.find(params[:id])
      render 'new'
    end
  end

  def show
    @offence = Offence.find(params[:id])
    @vehicleoffencecount = Offence.where(:offendingPlateNumber=>@offence.offendingPlateNumber).count("*")
    puts @vehicleoffencecount

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
    def offence_params
      params.require(:offence).permit(:offendingPlateNumber, :lot_id, :carpark_id)
    end
end

app/views/offences/index.html.erb
<div class="row">
	<div class="col-12 text-center">
		<h1>Offences</h1>
	</div>
</div>


		<div class="row">
		<div class= "col-1 border"><p>S/no</div>
		<div class = "col-2 border"><p>Carplate</p></div>
		<div class = "col-2 border"><p>Location</p></div>
		<div class = "col-2 border"><p>Lot Number</p></div>
		<div class = "col-2 border"><p>Date of Offense</p></div>
		<div class = "col-2 border"><p>View</p></div>
		</div>


		<% @offences.each_with_index do |offence, index| %>
		<div class="row">
		<div class= "col-1 border"><p><%= index %></p></div>
		<div class = "col-2 border"><%= offence.offendingPlateNumber %></div>
		<div class = "col-2 border"><%= offence.lot.carpark.location %></div>
		<div class = "col-2 border"><%= offence.lot.lotNumber %></div>
		<div class = "col-2 border"><%= offence.created_at %></div>
		<div class="col-2 border"><%= link_to 'View', offence_path(offence) %></div>
		</div>
		<% end %>

app/views/offences/new.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid main-content">
	<h2>Offensive attack</h2>

	<%= form_with scope: :offence, url: offences_path, local: true do |form| %>
	<div class="form-group">
		<h5>Location of offence: <%= @carpark.location %></h5>
		<%= form.collection_select :lot_id, @carpark.lots, :id, :lotNumber %>
	</div>
	<div class="form-group">
		<h5>Offending Plate Number</h5>
		<%= form.text_field :offendingPlateNumber %>
	</div>

	<div class="actions my-4">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

	<p><%= link_to 'Back', lots_path %></p>
	<% end %>
</div>

app/views/offences/show.html.erb
<h1>Show offence</h1>
<p> Vehicle number: <%= @offence.offendingPlateNumber %> </p>
<p> Carpark: <%= @offence.lot.carpark.location %></p>
<p> Illegal parking at lot <%= @offence.lot.lotNumber %></p>
<% if @vehicleoffencecount == 1 %>
<p>Number of offences: <%= @vehicleoffencecount %></p>
<p>Issue warning</p>
 <div class="alert alert-info">
    <span class="glyphicon glyphicon-info-sign"> </span>
    <strong> Alerted </strong> Send out warning letter.
    <button type="button" class="close" data-dismiss="alert"> &times; </button>
</div>
<script>alert('Alerted user about warning!')</script>
<% else %>
<% if @vehicleoffencecount == 2 %>
<p>Number of offences: <%= @vehicleoffencecount %></p>
<p>Issue Fine</p>
<div class="alert alert-info">
    <span class="glyphicon glyphicon-info-sign"> </span>
    <strong> Alerted </strong> Send out fine letter.
    <button type="button" class="close" data-dismiss="alert"> &times; </button>
</div>
<script>alert('Alerted user about fine!')</script>
<% else %>
<p>Number of offences: <%= @vehicleoffencecount %></p>
<p> Summon Infrit to clamp your car</p>
<div class="alert alert-info">
    <span class="glyphicon glyphicon-info-sign"> </span>
    <strong> Alerted </strong> Clamp user car.
    <button type="button" class="close" data-dismiss="alert"> &times; </button>
</div>
<script>alert('Alerted user about car clamp!')</script>
<% end %>
<% end %>
<%= link_to 'Back', offences_path %>