config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :summons, controllers: { sessions: "summons/sessions", registrations: "summons/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Main Paths
  root 'homes#landing'

  get '/login/role' => 'homes#loginrole'
  get '/signup/role' => 'homes#signuprole'


  # User Paths
  get '/vehicles' => 'vehicles#index', as: 'user'



  get '/carparks' => 'carparks#index', as: 'carparks'
  get '/carparks/new' => 'carparks#new', as: 'new_carpark'
  post '/carparks' => 'carparks#create'
  get '/carparks/:id' => 'carparks#show' , as: 'carpark'
  get '/carparks/:id/edit' => 'carparks#edit', as: 'edit_carpark'
  patch '/carparks/:id' => 'carparks#update'
  delete '/carparks/:id' => 'carparks#destroy'

  get '/carparks/:id/lots' => 'lots#index', as: 'lots'
  get '/carparks/:id/lots/new' => 'lots#new', as: 'new_lot'
  post '/carparks/:id/lots' => 'lots#create'
  get '/lots/:id' => 'lots#show' , as: 'lot'
  get '/lots/:id/edit' => 'lots#edit', as: 'edit_lot'
  patch '/lots/:id' => 'lots#update'
  delete '/lots/:id' => 'lots#destroy'


  get '/regions' => 'regions#index', as: 'regions'
  #get '/regions/new' => 'regions#new', as: 'new_region'
  #post '/regions' => 'regions#create'
  get '/regions/:id' => 'regions#show' , as: 'region'
  #get '/regions/:id/edit' => 'regions#edit', as: 'edit_region'
  #patch '/regions/:id' => 'regions#update'
  #delete '/regions/:id' => 'regions#destroy'









  get 'carparks/:id/offences/' => 'offences#index', as: 'offences'
  get 'carparks/:id/offences/new' => 'offences#new', as: 'new_offence'
  post 'carparks/:id/offences/' => 'offences#create'
  get '/offences/:id' => 'offences#show' , as: 'offence'

  get '/admins/' => 'homes#index', as: 'admin'
  get '/summons/' => 'homes#landing', as: 'summon'
end

app/models/carpark.rb
class Carpark < ActiveRecord::Base
  has_many :lots
  has_many :vehicles, through: :lots
  belongs_to :region

  validates :location, presence: true, uniqueness: { case_sensitive: false }
  validates :totallots, presence: true, numericality: { only_integer: true }
#   validates :photo_url, presence: true
end

app/controllers/carparks_controller.rb
class CarparksController < ApplicationController
  before_action :authenticate_admin!, :except => [:show, :index, :edit, :update, :destroy]

  def index
    @carparks = Carpark.all
    @regions = Region.all
    @regions = @regions.order("regionname")
    @lots = Lot.where.not(vehicle_id: nil)
    puts @lots.inspect
    @lots.each do |lot|
      #calculation in seconds. Will use a conditional to remove user id and vehicle id from lots
      puts lot.lotNumber
      puts lot.updated_at
      puts Time.new.utc
      puts Time.new.utc - lot.updated_at

    end



  end


  def new
    @carpark = Carpark.new
    @regions = Region.all
  end

  def create
    @carpark = Carpark.new(carpark_params)

    if @carpark.save
      redirect_to @carpark
    else
      render 'new'
    end
  end

  def show
      @carpark = Carpark.find(params[:id])

      @remaining = @carpark.totallots - @carpark.reservedlots
  end

def edit
  @carpark = Carpark.find(params[:id])
  @vehicles = Vehicle.all.where(:user_id => current_user)
  @lots = @carpark.lots.where(taken: false)
  @usedlots = @carpark.lots.where(taken: true)
  puts "in the edit path"
end

def update
  puts "in the weird update path"
  @carpark = Carpark.find(params[:id])
  @lot = Lot.find(params[:carpark].values[0].to_i)
  puts params
  puts params[:carpark].values[0]
    puts params[:carpark].values[1]
  puts @carpark.location
  puts @lot.lotNumber
  if @carpark.update(reservedlots: @carpark.reservedlots+1) && @lot.update(vehicle_id: params[:carpark].values[1].to_i) && @lot.update(taken: true)
    redirect_to carparks_path
  else
      @carpark = Carpark.find(params[:id])
  @vehicles = Vehicle.all.where(:user_id => current_user)
  @lots = @carpark.lots.where(taken: false)
  @usedlots = @carpark.lots.where(taken: true)
    render 'edit'
  end

end

  def destroy
      #if Boardfollowee.exists?(user_id: current_user.id, boardfollowee_id: params[:id] )
      #puts "does exist"
      #  @boardfollowee = Boardfollowee.find_by user_id: current_user.id, boardfollowee_id: params[:id]
      puts "Test for method"
      @lot = Lot.find(params[:carpark].values[0].to_i)
      puts @lot.lotNumber
      @carpark = Carpark.find(params[:id])
      @vehicle = @lot.vehicle
      #puts @vehicle.id
      #@newlot = Lot.new(:lotNumber => @lot.lotNumber)
      #@newlot.carpark = @carpark
      #@newlot.vehicle = nil
      #@newlot.save
      #puts @newlot.errors.full_messages
      #puts @newlot.lotNumber
       #     @newlot.carpark = @carpark
       #     @newlot.save
      @lot.update(:vehicle_id => nil)

      @carpark.update(reservedlots: @carpark.reservedlots-1)
      @lot.update(taken: false)


      redirect_to carparks_path
    #else
    #  puts "does not exist"


    #  redirect_to others_path
    #end




  end

private

  def carpark_params
    params.require(:carpark).permit(:location, :totallots, :photo_url, :region_id)
  end

end

app/views/carparks/edit.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid main-content">
	<h2>Confirmation</h2>

	<% if @carpark.errors.any? %>
	<div id="error_explanation">
		<h5 class="text-danger">
			<%= pluralize(@carpark.errors.count, "error") %> occurred:
		</h5>
		<ul>
			<% @carpark.errors.full_messages.each do |msg| %>
			<li class="text-danger"><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= form_with scope: :carpark, model: @carpark, local: true do |form| %>

	<p> Apply for season parking at <%= @carpark.location %> </p>
	<% if false %>
	<% @usedlots.each do |usedlot| %>
	<% puts usedlot.vehicle.license_plate %>
	<% if usedlot.vehicle.user.id == current_user.id && usedlot.carpark_id == params[:id].to_i %>
	<p>*Vehicle <strong><%= usedlot.vehicle.license_plate %></strong> has a valid season parking lot <strong>(<%= usedlot.lotNumber %>)</strong> at this carpark.</p>
	<% end %>
	<div class="form-group">
		<%= form.collection_select :lot_id, @lots, :id, :lotNumber, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.collection_select :vehicle_id, @vehicles, :id, :license_plate, class: "form-control" %>
	</div>
	<% end %>
	<% end %>

	<p>Register?</p>
	<div class="form-group">
		<%= form.collection_select :lot_id, @lots, :id, :lotNumber, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.collection_select :vehicle_id, @vehicles, :id, :license_plate, class: "form-control" %>
	</div>

	<div class="actions my-4">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

	<% end %>

	<%= form_for @carpark, method: :delete do |f| %>
	<p>Delete?</p>
	<div class="form-group">
		<%= f.collection_select :lot_ids, @usedlots, :id, :lotNumber, class: "form-control" %>
	</div>
	<div class="actions my-4">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
	<% end %>

	<%= link_to 'Back', carparks_path %>
</div>

app/views/carparks/index.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid main-content w-75">
	<h2>All Carparks</h2>

	<div class="row">
		<div class="col-12">
			<h3><%= Date.today %></h3>
		</div>
	</div>
	<div class ="row">
		<% if current_admin %>
		<div class="col-4 text-center ">
			<div><%= link_to 'Add New carpark', new_carpark_path %></div>
		</div>
		<% end %>
		<div class="col-4 text-right my-auto	">
			<p>Find carpark by region: </p>
		</div>
		<div class="col-4 text-center classname border">
			<% @regions.each do |region| %>

			<div><%= link_to region.regionname, region_path(region) %></div>
			<% end %>
		</div>
	</div>

	<div class="row">
		<br/>
		<% @carparks.each do |carpark| %>
		<div class="col-3 border">
			<div>Carpark name: <%= carpark.location %></div>
			<div>Region: <%= carpark.region.regionname %></div>
			<div><%= link_to 'Show', carpark_path(carpark) %></div>


			<% if carpark.totallots - carpark.reservedlots == 0 %>
			<div>	No more season parking lots. Try again another time </div>
			<div class="col-3">
				<div><%= link_to 'Remove season parking', edit_carpark_path(carpark) %></div>
			</div>

			<% elsif carpark.reservedlots == 0 %>
			<div><%= link_to 'Apply for season parking', edit_carpark_path(carpark) %></div>

			<% else %>

			<div><%= link_to 'Apply for season parking', edit_carpark_path(carpark) %></div>
			<% end %>
			<br/>
			<br/>
		</div>
		<% end %>

	</div>
</div>

app/views/carparks/new.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid main-content">
	<h2>Add New Carpark</h2>

	<%= form_with scope: :carpark, url: carparks_path, local: true do |form| %>
	<% if @carpark.errors.any? %>
	<div id="error_explanation">
		<h5 class="text-danger">
			<%= pluralize(@carpark.errors.count, "error") %> occurred:
		</h5>
		<ul>
			<% @carpark.errors.full_messages.each do |msg| %>
			<li class="text-danger"><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="form-group">
		<div class="field">
			<%= form.label :region %><br>
			<%= form.collection_select :region_id, @regions, :id, :regionname %>
		</div>
	</div>

	<div class="form-group my-4">
		<div class="field">
			<%= form.text_field :location, placeholder: "Location" %>
		</div>
	</div>

	<div class="form-group my-4">
		<div class="field">
			<%= form.text_field :totallots, placeholder: "Total Lots" %>
		</div>
	</div>

	<div class="form-group my-4">
		<div class="field">
			<%= form.text_field :photo_url, placeholder: "Photo URL" %>
		</div>
	</div>

	<div class="actions my-4">
		<button type="submit" class="btn btn-primary">Save Carpark</button>
	</div>

	<p><%= link_to 'Back', carparks_path %></p>
	<% end %>
</div>

app/views/carparks/show.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid my-5 w-75">
	<div class="row my-5">
		<div class = "col-12 text-center">
			<h2>Location: <%= @carpark.location %></h2>

		</div>

	</div>


	<div class="row">
		<div class = "col-12 text-center">


			<img src=<%= @carpark.photo_url %> alt="Carpark image" width="50%" height="100%"/>
		</div>

	</div>


	<div class="row mt-5">
		<div class = "col-6 text-center ">
			<strong>Lots taken:</strong>
			<%= @carpark.reservedlots %>
		</div>
		<div class = "col-6 text-center ">
			<strong>Lots remaining:</strong>
			<%= @carpark.totallots - @carpark.reservedlots %>
		</div>
	</div>

	<div class=" row">
		<% @carpark.lots.each do |lot| %>

		<div class="col-4 border text-center"><%= lot.lotNumber %><br/>
			<% if lot.taken %>
			Taken by <%= lot.vehicle.license_plate %></div>
			<% else %>
		Not Taken</div>
		<% end %>
		<% end %>
	</div>


	<div class="row">
		<div class = "col-12 text-center">
			<% if @carpark.totallots - @carpark.reservedlots == 0 %>
			<div>	No more season parking lots. Try again another time </div>

			<div class="col-3">
				<%= link_to 'Apply season parking', edit_carpark_path(@carpark), class: "btn btn-primary"%>
			</div>
			<% elsif @carpark.reservedlots == 0 %>
			<div class="row">
				<%= link_to 'Apply season parking', edit_carpark_path(@carpark), class: "btn btn-primary"%>
			</div>
			<% else %>
			<%= link_to 'Apply/Remove season parking', edit_carpark_path(@carpark), class: "btn btn-primary"%>
			<% end %>
		</div>
	</div>

	<div class= "row">
		<div class = "col-6 text-center"><%= link_to 'View lot', lots_path, class: "btn btn-info" %></div>
		<div class = "col-6 text-center"><%= link_to 'New lot', new_lot_path, class: "btn btn-info" %></div>
	</div>

	<div class = "row">
		<div class = " col-12 text-center">
			<%= link_to 'Back', carparks_path %>
		</div>
	</div>
</div>