config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :summons, controllers: { sessions: "summons/sessions", registrations: "summons/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Main Paths
  root 'homes#landing'

  get '/login/role' => 'homes#loginrole'
  get '/signup/role' => 'homes#signuprole'


  # User Paths
  get '/vehicles' => 'vehicles#index', as: 'user'



  get '/carparks' => 'carparks#index', as: 'carparks'
  get '/carparks/new' => 'carparks#new', as: 'new_carpark'
  post '/carparks' => 'carparks#create'
  get '/carparks/:id' => 'carparks#show' , as: 'carpark'
  get '/carparks/:id/edit' => 'carparks#edit', as: 'edit_carpark'
  patch '/carparks/:id' => 'carparks#update'
  delete '/carparks/:id' => 'carparks#destroy'

  get '/carparks/:id/lots' => 'lots#index', as: 'lots'
  get '/carparks/:id/lots/new' => 'lots#new', as: 'new_lot'
  post '/carparks/:id/lots' => 'lots#create'
  get '/lots/:id' => 'lots#show' , as: 'lot'
  get '/lots/:id/edit' => 'lots#edit', as: 'edit_lot'
  patch '/lots/:id' => 'lots#update'
  delete '/lots/:id' => 'lots#destroy'


  get '/regions' => 'regions#index', as: 'regions'
  #get '/regions/new' => 'regions#new', as: 'new_region'
  #post '/regions' => 'regions#create'
  get '/regions/:id' => 'regions#show' , as: 'region'
  #get '/regions/:id/edit' => 'regions#edit', as: 'edit_region'
  #patch '/regions/:id' => 'regions#update'
  #delete '/regions/:id' => 'regions#destroy'









  get 'carparks/:id/offences/' => 'offences#index', as: 'offences'
  get 'carparks/:id/offences/new' => 'offences#new', as: 'new_offence'
  post 'carparks/:id/offences/' => 'offences#create'
  get '/offences/:id' => 'offences#show' , as: 'offence'

  get '/admins/' => 'homes#index', as: 'admin'
  get '/summons/' => 'homes#landing', as: 'summon'
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @carparks = Carpark.all
  end

  def landing
  end

  def about
  end

  def loginrole
  end

  def signuprole
  end
end

app/views/homes/index.html.erb
<% if admin_signed_in? %>
	<div id="navbar" class="d-flex justify-content-between">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>

		<div id="user-actions" class="my-2">
			<nav class="navbar navbar-expand">
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item">
							<%= link_to 'Log Out', destroy_admin_session_url, method: :delete, :class=>"nav-link" %>
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>

	<h2>FM Dashboard</h2>
	<br>
	<%= link_to 'All Carparks', carparks_path, :class => 'btn btn-primary' %>
	<%= link_to 'All Regions', regions_path, :class => 'btn btn-secondary' %>
	<br><br>
	<table class='table'>
		<thead>
			<tr>
				<th scope='col'>Carparks</th>
				<th scope='col'>Region</th>
				<th scope='col'>Postal Code</th>
				<th scope='col'>Occupancy</th>
			</tr>
		</thead>
		<tbody>
			<% @carparks.each do |carpark| %>
				<tr>
					<td><%= link_to carpark.location, carpark_path(carpark) %></td>
					<td><%= carpark.region.regionname %></td>
					<td><%= carpark.region.postalcode %></td>
					<td><%= carpark.reservedlots %> / <%= carpark.totallots %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

<% else %>
	<div id="navbar" class="d-flex justify-content-between">
    <a href="/">
      <div id="logo">
        <%= image_tag 'logo.png', style: 'height: 100%;' %>
      </div>
    </a>

	<div id="user-actions" class="my-2">
		<nav class="navbar navbar-expand">
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="/login/role">LOG IN</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/signup/role">SIGN UP</a>
					</li>
				</ul>
			</div>
		</nav>
	</div>

	<div id="cover" class="container-fluid p-0 w-100">
		<div class="row no-gutter align-items-center m-0">
			<div class="col text-center p-0 d-flex align-items-center">
				<%= image_tag 'cover.jpg', class: "w-100 img-fluid position-relative mx-auto", style: 'opacity: 0.8;'%>
				<div id="title" class="w-100 position-absolute my-auto">
					<div>
						<h1>ParkingGoWhere</h1>
						<h2>Season Parking Simplified.</h2>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/homes/landing.html.erb
<div id="navbar" class="d-flex justify-content-between">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>

	<nav class="navbar navbar-expand">
		<ul class="navbar-nav">
			<% unless current_user || current_admin || current_summon %>
			<li class="nav-item">
				<a class="nav-link" href="/login/role">LOG IN</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/signup/role">SIGN UP</a>
			</li>
			<% end %>
		</ul>
	</nav>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div id="cover" class="container-fluid p-0 w-100">
	<div class="row no-gutter align-items-center m-0">
		<div class="col text-center p-0 d-flex align-items-center">
			<%= image_tag 'cover.jpg', class: "w-100 img-fluid position-relative mx-auto", style: 'opacity: 0.8;'%>
			<div id="title" class="w-100 position-absolute my-auto">
				<div>
					<h1>ParkingGoWhere</h1>
					<h2>Season Parking Simplified.</h2>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/homes/loginrole.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<div class="container-fluid main-content">
	<h2>Are you a...?</h2>
	<div class="card-wrapper d-flex w-100 justify-content-around">
		<div class="col role-card">
			<%= image_tag "user.jpg", class: "image" %>
			<a href="/users/sign_in">
				<div class="overlay">
					<div class="text">Vehicle Owner</div>
				</div>
			</a>
		</div>
		<div class="col role-card">
			<%= image_tag "carpark.jpg", class: "image" %>
			<a href="/admins/sign_in">
				<div class="overlay">
					<div class="text">Facilities Manager</div>
				</div>
			</a>
		</div>
		<div class="col role-card">
			<%= image_tag "warden.jpg", class: "image" %>
			<a href="/summons/sign_in">
				<div class="overlay">
					<div class="text">Parking Warden</div>
				</div>
			</a>
		</div>
	</div>
</div>

app/views/homes/role.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<div id="logo">
		<a href="/">PLACEHOLDER</a>
	</div>
</div>

<div class="container-fluid">
	<h2 class="my-5">Are you a...?</h2>
	<div class="card-wrapper d-flex w-100 justify-content-around">
		<div class="col role-card">
			<%= image_tag "user.jpg", class: "image" %>
			<a href="/users/sign_up">
				<div class="overlay">
					<div class="text">Vehicle Owner</div>
				</div>
			</a>
		</div>
		<div class="col role-card">
			<%= image_tag "carpark.jpg", class: "image" %>
			<a href="/admins/sign_up">
				<div class="overlay">
					<div class="text">Facilities Manager</div>
				</div>
			</a>
		</div>
		<div class="col role-card">
			<%= image_tag "warden.jpg", class: "image" %>
			<a href="/summons/sign_up">
				<div class="overlay">
					<div class="text">Parking Warden</div>
				</div>
			</a>
		</div>
	</div>
</div>

app/views/homes/signuprole.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<div class="container-fluid main-content">
	<h2>Are you a...?</h2>
	<div class="card-wrapper d-flex w-100 justify-content-around">
		<div class="col role-card">
			<%= image_tag "user.jpg", class: "image" %>
			<a href="/users/sign_up">
				<div class="overlay">
					<div class="text">Vehicle Owner</div>
				</div>
			</a>
		</div>
		<div class="col role-card">
			<%= image_tag "carpark.jpg", class: "image" %>
			<a href="/admins/sign_up">
				<div class="overlay">
					<div class="text">Facilities Manager</div>
				</div>
			</a>
		</div>
		<div class="col role-card">
			<%= image_tag "warden.jpg", class: "image" %>
			<a href="/summons/sign_up">
				<div class="overlay">
					<div class="text">Parking Warden</div>
				</div>
			</a>
		</div>
	</div>
</div>