config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :summons, controllers: { sessions: "summons/sessions", registrations: "summons/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Main Paths
  root 'homes#landing'

  get '/login/role' => 'homes#loginrole'
  get '/signup/role' => 'homes#signuprole'


  # User Paths
  get '/vehicles' => 'vehicles#index', as: 'user'



  get '/carparks' => 'carparks#index', as: 'carparks'
  get '/carparks/new' => 'carparks#new', as: 'new_carpark'
  post '/carparks' => 'carparks#create'
  get '/carparks/:id' => 'carparks#show' , as: 'carpark'
  get '/carparks/:id/edit' => 'carparks#edit', as: 'edit_carpark'
  patch '/carparks/:id' => 'carparks#update'
  delete '/carparks/:id' => 'carparks#destroy'

  get '/carparks/:id/lots' => 'lots#index', as: 'lots'
  get '/carparks/:id/lots/new' => 'lots#new', as: 'new_lot'
  post '/carparks/:id/lots' => 'lots#create'
  get '/lots/:id' => 'lots#show' , as: 'lot'
  get '/lots/:id/edit' => 'lots#edit', as: 'edit_lot'
  patch '/lots/:id' => 'lots#update'
  delete '/lots/:id' => 'lots#destroy'


  get '/regions' => 'regions#index', as: 'regions'
  #get '/regions/new' => 'regions#new', as: 'new_region'
  #post '/regions' => 'regions#create'
  get '/regions/:id' => 'regions#show' , as: 'region'
  #get '/regions/:id/edit' => 'regions#edit', as: 'edit_region'
  #patch '/regions/:id' => 'regions#update'
  #delete '/regions/:id' => 'regions#destroy'









  get 'carparks/:id/offences/' => 'offences#index', as: 'offences'
  get 'carparks/:id/offences/new' => 'offences#new', as: 'new_offence'
  post 'carparks/:id/offences/' => 'offences#create'
  get '/offences/:id' => 'offences#show' , as: 'offence'

  get '/admins/' => 'homes#index', as: 'admin'
  get '/summons/' => 'homes#landing', as: 'summon'
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  belongs_to :carpark
  belongs_to :vehicle, optional: true
  has_many :offences
  validates :lotNumber, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
 before_action :authenticate_admin!, :except => [:show, :index]
  def index
    @carpark = Carpark.find(params[:id])
    puts @carpark.lots.count
  end


  def new
    @lot = Lot.new
    @carparks = Carpark.all
  end

  def create
    @lot = Lot.new(lot_params)
    puts " i have entered here"
    @carpark = Carpark.find(params[:id])
    @lot.carpark = @carpark
    if @lot.save && @carpark.update(totallots: @carpark.lots.count)
      redirect_to @lot
    else
      render 'new'
    end
  end

  def show
      @lot = Lot.find(params[:id])

  end

def edit
  @lot = Lot.find(params[:id])

  puts "in the edit path"
end

def update
@lot = Lot.find(params[:id])
@lot.update(lot_params)
redirect_to @lot
end

  def destroy
      #if Boardfollowee.exists?(user_id: current_user.id, boardfollowee_id: params[:id] )
      #puts "does exist"
      #  @boardfollowee = Boardfollowee.find_by user_id: current_user.id, boardfollowee_id: params[:id]
      @lot = Lot.find(params[:id])



      @lot.destroy

      redirect_to carparks_path
      # @carpark.update(reservedlots: @carpark.reservedlots-1)
      # redirect_to carparks_path
    #else
    #  puts "does not exist"


    #  redirect_to others_path
    #end




  end

private

  def lot_params
    params.require(:lot).permit(:lotNumber)
  end

end

app/views/lots/edit.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid main-content">
	<h2>Edit Lot</h2>

	<%= form_with scope: :lot,model: @lot, local: true do |form| %>

	<p>
		<h5>Lot Number</h5>
		<%= form.text_field :lotNumber %>
	</p>



	<div class="actions my-4">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

	<p><%= link_to 'Back', lots_path %></p>
	<% end %>
</div>

app/views/lots/index.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid my-5 w-75">
	<div class="my-5">
		<h2>Lot Admin Page</h2>

		<h4>Car Park Location:  <%= @carpark.location %></h4>

		<h4>Lots allocated:  <%= @carpark.lots.count %></h4>
	</div>

	<div class ="row my-5">
		<% @carpark.lots.each do |lot| %>
		<div class = "col-3 text-center border pt-4 pb-4">
			<div><%= lot.lotNumber %></div>
			<% if lot.taken %>
			<div>Status: Taken</div>
			<div>Owner: <%= lot.vehicle.license_plate %></div>
			<div>Since: <%= lot.updated_at %></div>
			<div>Expiry: <%= lot.updated_at + 28.days %></div>
			<% else %>
			<div>Status: Not Taken</div>
			<% end %>
			<div><%= link_to 'Edit Lot', edit_lot_path(lot) %></div>
			<p><%= link_to 'Remove lot', lot_path(lot),
			method: :delete,
			data: { confirm: 'Are you sure?' } %></p>
			<%= link_to 'Report', new_offence_path, class: "btn btn-primary"%>
		</div>
		<% end %>
	</div>

	<p><%= link_to 'Back to Carpark', carpark_path %></p>
</div>

app/views/lots/new.html.erb
<div id="navbar" class="d-flex justify-content-center role-nav">
	<a href="/">
		<div id="logo">
			<%= image_tag 'logo.png', style: 'height: 100%;' %>
		</div>
	</a>
</div>

<% if current_user || current_admin || current_summon %>
<nav class="navbar navbar-expand bg-light">
	<% if current_user %>
	<ul class="navbar-nav">
		<li class="nav-item form-inline">
			Welcome, &nbsp;<strong><%= current_user.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Vehicles
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'My Vehicles', vehicles_path(user: current_user), :class => "dropdown-item" %>
				<%= link_to 'Add New Vehicle', new_vehicle_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_admin %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_admin.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Carparks
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
				<%= link_to 'All Carparks', carparks_path, :class => "dropdown-item" %>
				<%= link_to 'Add New Carpark', new_carpark_path, :class => "dropdown-item" %>
			</div>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_admin_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% elsif current_summon %>
	<ul class="navbar-nav">
		<li class="nav-item active form-inline">
			Welcome, &nbsp;<strong><%= current_summon.email.split('@')[0] %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</li>
	</ul>

	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<%= link_to 'Carparks', carparks_path, :class => "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to 'Regions', regions_path, :class => "nav-link" %>
		</li>
	</ul>

	<ul class="navbar-nav">
		<li class="nav-item">
			<%= link_to 'LOG OUT', destroy_summon_session_path, method: :delete, class: "nav-link" %>
		</li>
	</ul>
	<% end %>
</nav>
<% end %>

<div class="container-fluid main-content">
	<h2>Add New Lot</h2>

	<%= form_with scope: :lot, url: lots_path, local: true do |form| %>
	<% if @lot.errors.any? %>
	<div id="error_explanation">
		<h5 class="text-danger">
			<%= pluralize(@lot.errors.count, "error") %> occurred:
		</h5>
		<ul>
			<% @lot.errors.full_messages.each do |msg| %>
			<li class="text-danger"><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="form-group">
		<div class="field">
			<%= form.text_field :lotNumber, placeholder: "Lot Number" %>
		</div>
	</div>

	<div class="actions my-4">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>

	<p><%= link_to 'Back', carpark_path %></p>
	<% end %>
</div>

app/views/lots/show.html.erb
<h1>Test</h1>
<p>Lot Number : <%= @lot.lotNumber %></p>
<p>Carpark location : <%= @lot.carpark.location %> </p>
<% if @lot.taken %>
	<p>Taken by car plate: <%= @lot.vehicle.license_plate %></p>
	<% else %>
	<p>Not taken</p>
	<% end %>

<h1>Summon infrit to destroy the illegal car</h1>